name: pangene
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - miniprot
  - k8
  - biopython
  - pandas
  - blast
  - numpy
  - seaborn
  - matplotlib
  - yaml
  - diamond
  - seqtk
  - pip:
    - pangene
